kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ValidatingAdmissionPolicy": true
  "AggregatedDiscoveryEndpoint": true
runtimeConfig:
  "api/alpha": "true"
nodes:
- role: control-plane