kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /opt/kind/cni
      containerPath: /opt/cni/bin
- role: worker
  extraMounts:
    - hostPath: /opt/kind/cni
      containerPath: /opt/cni/bin