name: deploy ghpage

on:
  pull_request:
  push:
    branches: [ source ]
  schedule:
  - cron: "0 9 * * *"

jobs:

  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1

      - name: Sync lank8s 
        run: |
            git clone https://liangyuanpeng:${{ secrets.GITEE_PASSWORD }}@github.com/lank8s/.github.git lank8sprofile
            cat content/post/cncf/kubernetes/top/lank8s.md > lank8sprofile/profile/README.md
            git clone https://liangyuanpeng:@github.com/lank8scn/lank8scn.git lank8scn
            cat content/post/cncf/kubernetes/top/lank8s.md > lank8scn/README.md